# =====================================
# configuration base de donnees / perso
# =====================================
spring.datasource.url=jdbc:mysql://localhost:3306/mabaseperso?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mdproot456

# =====================================
# jpa configuration
# =====================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# =====================================
# serveur
# =====================================
server.port=8080
server.servlet.context-path=/monapi